### ISSUE TITLE
Internal error (box 28?)

### ISSUE THREAD

**Issue by erasare** [sofar/minetest.foo-projects.org#1]
Hi,

don't know exactly if i provoked the internal, but here it is:

Went into 28, pushed the two buttons, got the nexus,
went into the ruine and climebed the stairs.
Looked like the piston was not working.

-> internal error

**Comment by erasare** [comment]
Sorry, now it's working already.
Perhaps it wasn't me :/

**Comment by sofar** [comment]
You just happened to be online when the crash occurred, it was unrelated to your gameplay.

**Comment by sofar** [comment]
FYI the issue causing the crash has since been identified and fixed.
