### ISSUE TITLE
Server lag

### ISSUE THREAD

**Issue by EmeraldMT** [sofar/minetest.foo-projects.org#13]
Server has been experiencing intermittent spikes in the max_lag of up to 43 seconds. This tends to cause boxes to load very slowly upon entering to edit or play. You've seen screenshots of how this looks for me. Doesn't appear to relate to number of players on the server as it happens when I'm the only one there, too. Hasn't been causing me to fall out of the box, unless I fly out the unloaded parts (which is my own fault of course).

**Comment by sofar** [comment]
Closing really old bug for now. Not sure if this is still an issue.
