### ISSUE TITLE
Node text showing as black panes.

### ISSUE THREAD

**Issue by FunDuels** [sofar/minetest.foo-projects.org#15]
Where there should be text, there is a black pane. I don't appear to have any debug messages.

As a side note, this is the first server I've played on since upgrading to version 5 of minetest. So it could be a problem on my end.

![itbErrorImage1](https://user-images.githubusercontent.com/74631365/99465801-1ba25500-2909-11eb-866f-4a112312c0a3.png)
![itbErrorImage2](https://user-images.githubusercontent.com/74631365/99465873-3aa0e700-2909-11eb-99ea-345ef20d941b.png)

**Comment by sofar** [comment]
very strange. the font characters used here are sent as textures to the client, and this method is normally supported by pretty much all clients, even 0.4.x. What client/OS are you using?

**Comment by FunDuels** [comment]
The client is 5.3.0 and I'm on FreeBSD.

**Comment by FunDuels** [comment]
I'm guessing the problem is on my end. Wasn't sure if it was just me before.
