### ISSUE TITLE
Add new HUD with amount of collected nexuses/total nexuses

### ISSUE THREAD

**Issue by Reedych** [sofar/minetest.foo-projects.org#2]
To see how many nexus blocks I need.

**Comment by sofar** [comment]
You mean, for when you're playing, right?

I don't think I want to do that. It would remove a large amount of "surprise" elements that puzzles can bring, and possibly spoil some of the puzzles that already exist.

**Comment by sofar** [comment]
Closing this as 'unwanted'. It is up to builders to decide whether they want to reveal the amount or not.
