### ISSUE TITLE
Fastest play time sign at box entrance

### ISSUE THREAD

**Issue by pauloue** [sofar/minetest.foo-projects.org#4]
A sign that said something like "Fastest play: 4min 20sec (player name)" at the box entrance would be nice to add some competition and give people more of a reason to replay boxes. I imagine this wouldn't be too hard since play times are already recorded.

**Comment by sofar** [comment]
I don't want to make the game too competitive, and putting up big signs showing how well other people did on their 25th attempt when you're trying a box for the first time, would be a really good way to make people feel depressed about their abilities.

Sorry, no thanks.
