### ISSUE TITLE
inside a box

### ISSUE THREAD

**Issue by PowerOlive** [sofar/minetest.foo-projects.org#6]
is inside a box open source?

**Comment by sofar** [comment]
Soon. I need to finish reviewing licensing statements and attributions, then the code will be published.

**Comment by PowerOlive** [comment]
thanks your reply sofar
but when i build in your server i can fly and fly out of the box...
lets be friend
oh i donot use it for ivil:)

**Comment by PowerOlive** [comment]
i donot like html i like code!!! haha

**Comment by PowerOlive** [comment]
ive make a folder in my desktop waiting your code!:)

**Comment by PowerOlive** [comment]
is inside a box open source?

**Comment by sofar** [comment]
Can you explain how you manage to fly in and out of a box while building? If possible, maybe you can show me while we're both on the server?

**Comment by PowerOlive** [comment]
sofar: use github.com/zaoqi/minetest-cheat when i am creating a box

**Comment by PowerOlive** [comment]
> 
> 
> Soon. I need to finish reviewing licensing statements and attributions, then the code will be published.

it's 2019 now

**Comment by sofar** [comment]
code was published ages ago.

**Comment by PowerOlive** [comment]
https://gitlab.com/sofar/insidethebox
