### ISSUE TITLE
Box 260 issue

### ISSUE THREAD

**Issue by EmeraldMT** [sofar/minetest.foo-projects.org#7]
Discovered by James7, confirmed by me.

Issue: We managed to break the box so it could not be completed. After getting the first nexus we can prevent getting the second nexus.

Steps to reproduce:

Near the exit doors, press the switches to get the first nexus. Place it on a pedestal.

Hit the switches again, but instead of getting the 2nd nexus, open the first chest again.

The switches will no longer work and the 2nd chest can not be accessed. Player is now trapped in that area and cannot exit the box.

**Comment by sofar** [comment]
@ekdohibs this is your box, want me to try and see if there's a simple exclusion fix for this?

**Comment by Ekdohibs** [comment]
Thanks for the report!
@sofar if you see a simple solution, please do :) Otherwise I'll just try to fix it myself when I get some time.

**Comment by sofar** [comment]
Issue fixed.
